---
- name: Define o arquivo de configuração do RoundCube Debian
  copy: src=config.inc.php dest=/var/www/html/roundcubemail/config/config.inc.php owner=www-data group=www-data mode=0644
  when: (ansible_os_family == "Debian" and roundcube_installed|succeeded)
  notify:
    - Reload Apache

- name: Define o arquivo VirtualHost do RoundCube Debian
  copy: src=roundcubemail.conf dest=/etc/apache2/sites-available/roundcubemail.conf owner=www-data group=www-data mode=0644
  when: (ansible_os_family == "Debian" and php_packages_debian_installed|success)
  notify:
    - Reload Apache

- name: Define o arquivo de configuração do RoundCube CentOS
  copy: src=config.inc.php dest=/var/www/html/roundcubemail/config/config.inc.php owner=apache group=apache mode=0644
  when: (ansible_os_family == "RedHat" and roundcube_installed|succeeded)
  notify:
    - Reload Httpd

- name: Define o arquivo VirtualHost do RoundCube CentOS
  copy: src=roundcubemail.conf dest=/etc/httpd/conf.d/roundcubemail.conf owner=apache group=apache mode=0644
  when: (ansible_os_family == "RedHat" and php_packages_centos_installed|success)
  notify:
    - Reload Httpd

- name: Define o arquivo de configuração do LogAnalyzer Debian
  copy: src=config.php dest=/var/www/html/loganalyzer/config.php owner=www-data group=www-data mode=0644
  when: (ansible_os_family == "Debian" and roundcube_installed|succeeded)
  notify:
    - Reload Apache

- name: Define o arquivo VirtualHost do LogAnalyzer Debian
  copy: src=loganalyzer.conf dest=/etc/apache2/sites-available/loganalyzer.conf owner=www-data group=www-data mode=0644
  when: (ansible_os_family == "Debian" and php_packages_debian_installed|success)
  notify:
    - Reload Apache

- name: Define o arquivo de configuração do LogAnalyzer CentOS
  copy: src=config.php dest=/var/www/html/loganalyzer/config.php owner=apache group=apache mode=0644
  when: (ansible_os_family == "RedHat" and roundcube_installed|succeeded)
  notify:
    - Reload Httpd

- name: Define o arquivo VirtualHost do LogAnalyzer CentOS
  copy: src=loganalyzer.conf dest=/etc/httpd/conf.d/loganalyzer.conf owner=apache group=apache mode=0644
  when: (ansible_os_family == "RedHat" and php_packages_centos_installed|success)
  notify:
    - Reload Httpd
