---
- name: Instala servidor de E-mail da empresa Dexter Courier
  apt: pkg={{item}} state=installed update_cache=true
  with_items:
    - postfix
    - courier-pop
    - courier-imap
  register: postfix_packages_installed
  notify:
    - Start Postfix
